package com.noandroid.familycontacts.model;

import java.util.List;
import com.noandroid.familycontacts.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONTACT".
 */
public class Contact {

    private Long id;
    /** Not-null value. */
    private String name;
    private String relationship;
    private boolean avatar;
    private String pinyin;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ContactDao myDao;

    private List<Telephone> telephones;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, String name, String relationship, boolean avatar, String pinyin) {
        this.id = id;
        this.name = name;
        this.relationship = relationship;
        this.avatar = avatar;
        this.pinyin = pinyin;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getContactDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getRelationship() {
        return relationship;
    }

    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    public boolean getAvatar() {
        return avatar;
    }

    public void setAvatar(boolean avatar) {
        this.avatar = avatar;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Telephone> getTelephones() {
        if (telephones == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TelephoneDao targetDao = daoSession.getTelephoneDao();
            List<Telephone> telephonesNew = targetDao._queryContact_Telephones(id);
            synchronized (this) {
                if(telephones == null) {
                    telephones = telephonesNew;
                }
            }
        }
        return telephones;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTelephones() {
        telephones = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

    public Contact(Long id, String name, String relationship, boolean avatar) {
        this.id = id;
        this.name = name;
        this.relationship = relationship;
        this.avatar = avatar;
        this.pinyin = Pinyin.getPinyinForString(this.name);
    }

    public Contact(Long id, String name, String relationship) {
        this.id = id;
        this.name = name;
        this.relationship = relationship;
        this.avatar = false;
        this.pinyin = Pinyin.getPinyinForString(this.name);
    }

    public void setNameAndPinyin(String name) {
        this.name = name;
        this.pinyin = Pinyin.getPinyinForString(name);
    }
    // KEEP METHODS END

}
