package com.noandroid.familycontacts.model;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.noandroid.familycontacts.model.RecordDao;
import com.noandroid.familycontacts.model.ContactDao;
import com.noandroid.familycontacts.model.CityDao;
import com.noandroid.familycontacts.model.TelephoneDao;
import com.noandroid.familycontacts.model.TelInitialDao;
import com.noandroid.familycontacts.model.BlacklistDao;
import com.noandroid.familycontacts.model.PinyinDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1001): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1001;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        RecordDao.createTable(db, ifNotExists);
        ContactDao.createTable(db, ifNotExists);
        CityDao.createTable(db, ifNotExists);
        TelephoneDao.createTable(db, ifNotExists);
        TelInitialDao.createTable(db, ifNotExists);
        BlacklistDao.createTable(db, ifNotExists);
        PinyinDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        RecordDao.dropTable(db, ifExists);
        ContactDao.dropTable(db, ifExists);
        CityDao.dropTable(db, ifExists);
        TelephoneDao.dropTable(db, ifExists);
        TelInitialDao.dropTable(db, ifExists);
        BlacklistDao.dropTable(db, ifExists);
        PinyinDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(RecordDao.class);
        registerDaoClass(ContactDao.class);
        registerDaoClass(CityDao.class);
        registerDaoClass(TelephoneDao.class);
        registerDaoClass(TelInitialDao.class);
        registerDaoClass(BlacklistDao.class);
        registerDaoClass(PinyinDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
