package com.noandroid.familycontacts.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PINYIN".
 */
public class Pinyin {

    private Long id;
    private String zi;
    private String pinyin;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Pinyin() {
    }

    public Pinyin(Long id) {
        this.id = id;
    }

    public Pinyin(Long id, String zi, String pinyin) {
        this.id = id;
        this.zi = zi;
        this.pinyin = pinyin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getZi() {
        return zi;
    }

    public void setZi(String zi) {
        this.zi = zi;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    // KEEP METHODS - put your custom methods here
    static public String getPinyinForString(String str) {
        DaoMaster daoMaster = new DaoMaster(DatabaseHelper.getDB(null).getReadableDatabase());
        PinyinDao pinyinDao = daoMaster.newSession().getPinyinDao();
        String res = "";
        for (int i = 0; i < str.length(); ++i) {
            char c = str.charAt(i);
            Pinyin py = pinyinDao.queryBuilder().where(PinyinDao.Properties.Zi.eq(c)).unique();
            res += py == null ? c : py.getPinyin();
        }
        return res;
    }
    // KEEP METHODS END

}
