package com.noandroid.familycontacts.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.noandroid.familycontacts.model.TelInitial;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEL_INITIAL".
*/
public class TelInitialDao extends AbstractDao<TelInitial, String> {

    public static final String TABLENAME = "TEL_INITIAL";

    /**
     * Properties of entity TelInitial.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Initial = new Property(0, String.class, "initial", true, "INITIAL");
        public final static Property TelinitCityId = new Property(1, Long.class, "telinitCityId", false, "TELINIT_CITY_ID");
    };

    private DaoSession daoSession;


    public TelInitialDao(DaoConfig config) {
        super(config);
    }
    
    public TelInitialDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEL_INITIAL\" (" + //
                "\"INITIAL\" TEXT PRIMARY KEY NOT NULL ," + // 0: initial
                "\"TELINIT_CITY_ID\" INTEGER);"); // 1: telinitCityId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEL_INITIAL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TelInitial entity) {
        stmt.clearBindings();
 
        String initial = entity.getInitial();
        if (initial != null) {
            stmt.bindString(1, initial);
        }
 
        Long telinitCityId = entity.getTelinitCityId();
        if (telinitCityId != null) {
            stmt.bindLong(2, telinitCityId);
        }
    }

    @Override
    protected void attachEntity(TelInitial entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TelInitial readEntity(Cursor cursor, int offset) {
        TelInitial entity = new TelInitial( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // initial
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1) // telinitCityId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TelInitial entity, int offset) {
        entity.setInitial(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTelinitCityId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(TelInitial entity, long rowId) {
        return entity.getInitial();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(TelInitial entity) {
        if(entity != null) {
            return entity.getInitial();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCityDao().getAllColumns());
            builder.append(" FROM TEL_INITIAL T");
            builder.append(" LEFT JOIN CITY T0 ON T.\"TELINIT_CITY_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TelInitial loadCurrentDeep(Cursor cursor, boolean lock) {
        TelInitial entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        City city = loadCurrentOther(daoSession.getCityDao(), cursor, offset);
        entity.setCity(city);

        return entity;    
    }

    public TelInitial loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TelInitial> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TelInitial> list = new ArrayList<TelInitial>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TelInitial> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TelInitial> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
