package com.example.admin.myapplication.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig cityDaoConfig;
    private final DaoConfig telephoneDaoConfig;
    private final DaoConfig telInitialDaoConfig;

    private final RecordDao recordDao;
    private final ContactDao contactDao;
    private final CityDao cityDao;
    private final TelephoneDao telephoneDao;
    private final TelInitialDao telInitialDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        telephoneDaoConfig = daoConfigMap.get(TelephoneDao.class).clone();
        telephoneDaoConfig.initIdentityScope(type);

        telInitialDaoConfig = daoConfigMap.get(TelInitialDao.class).clone();
        telInitialDaoConfig.initIdentityScope(type);

        recordDao = new RecordDao(recordDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        cityDao = new CityDao(cityDaoConfig, this);
        telephoneDao = new TelephoneDao(telephoneDaoConfig, this);
        telInitialDao = new TelInitialDao(telInitialDaoConfig, this);

        registerDao(Record.class, recordDao);
        registerDao(Contact.class, contactDao);
        registerDao(City.class, cityDao);
        registerDao(Telephone.class, telephoneDao);
        registerDao(TelInitial.class, telInitialDao);
    }
    
    public void clear() {
        recordDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        cityDaoConfig.getIdentityScope().clear();
        telephoneDaoConfig.getIdentityScope().clear();
        telInitialDaoConfig.getIdentityScope().clear();
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public TelephoneDao getTelephoneDao() {
        return telephoneDao;
    }

    public TelInitialDao getTelInitialDao() {
        return telInitialDao;
    }

}
